### ISSUE TITLE
EADDRINUSE mqtt 1883

### ISSUE THREAD

**Issue by kiralikbeyin** [marcoschwartz/aREST_UI#16]
Hi Everyone,

Keep in your mind if you are trying to run arest in local;

You will get this when you run meteor with mosquitto-->> Error: listen EADDRINUSE

Mosca is making trouble if mosquitto is running check it -->> sudo lsof -i tcp:1883
then -->> sudo kill -9 "PID"

Don't forget to run **mongod** if its not running you will get -->> Error: connect ECONNREFUSED

No problem with latest meteor 1.3.2.4 and mosca 1.3.0 and node v6.1.0 (npm v3.8.6) and mongodb

**Comment by marcoschwartz** [comment]
Great comment! But would you mind opening this on https://github.com/marcoschwartz/meteor-arest-mqtt ? It would more relevant :) Thanks!
