### ISSUE TITLE
Multiple warnings at Arduino IDE v1.8.n

### ISSUE THREAD

**Issue by flidget** [marcoschwartz/aREST_UI#26]
E.g.
../Arduino/libraries/aREST/aREST.h:1338:28: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
        addToBuffer(HARDWARE);

**Comment by marcoschwartz** [comment]
Hello,

Does that prevents you from using aREST or it's just a warning ? :)

**Comment by flidget** [comment]
:) it's not great to see warnings. However, the RTC libraries are in worse shape with this release (of the IDE)!
