### ISSUE TITLE
Arduino IDE not Accepting "ui."

### ISSUE THREAD

**Issue by ghost** [marcoschwartz/aREST_UI#4]
Hi,
Just now i was making a code but when i wrote "ui.button(2)" ( as defined in description) it gives an error and does not accept it, but when i try again with "rest.button(2)" it accepts it and compiles the code. 
Is it Okay?

Thanks & Regards,
Ayush

**Comment by marcoschwartz** [comment]
Hello, this is simply related to the instance name you are using for the aREST_UI instance. Check the declaration of the instance at the start of the code:

aREST_UI rest = aREST_UI();

Closing this as it's not related to the library itself :)
